/**
 * Project Profile YAML writer.
 *
 * Serializes a `ProjectProfile` object to YAML and writes it to the specified
 * path, prepending a comment header that documents the file purpose.
 */

import { writeFile } from 'fs/promises'
import yaml from 'js-yaml'
import type { ProjectProfile } from './project-profile.js'

// ---------------------------------------------------------------------------
// Comment header prepended to all generated profile files
// ---------------------------------------------------------------------------

const PROFILE_HEADER =
  '# Substrate Project Profile\n' +
  '# Generated by `substrate init`\n' +
  '# Edit to override auto-detected settings.\n' +
  '\n'

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Serializes the given `ProjectProfile` to YAML and writes it to `profilePath`.
 *
 * The generated file begins with a human-readable comment header so users can
 * understand the file's purpose at a glance. The YAML content is produced by
 * `js-yaml`'s `dump()` function for consistent formatting.
 *
 * @param profilePath - Absolute path to write the profile YAML file.
 * @param profile - The `ProjectProfile` object to serialize.
 */
export async function writeProjectProfile(
  profilePath: string,
  profile: ProjectProfile
): Promise<void> {
  const yamlContent = yaml.dump(profile)
  await writeFile(profilePath, PROFILE_HEADER + yamlContent, 'utf-8')
}
