/**
 * Unit tests for the project profile writer.
 *
 * Verifies that `writeProjectProfile` correctly:
 * - Prepends the comment header to the YAML output
 * - Serializes ProjectProfile fields correctly
 * - Handles monorepo profiles with packages arrays
 */

import { describe, it, expect, vi, beforeEach, type MockedFunction } from 'vitest'
import * as fsPromises from 'fs/promises'
import { writeProjectProfile } from '../writer.js'
import type { ProjectProfile } from '../project-profile.js'

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

vi.mock('fs/promises')

const mockWriteFile = fsPromises.writeFile as MockedFunction<typeof fsPromises.writeFile>

beforeEach(() => {
  vi.clearAllMocks()
  mockWriteFile.mockResolvedValue(undefined)
})

// ---------------------------------------------------------------------------
// Header verification
// ---------------------------------------------------------------------------

describe('writeProjectProfile — comment header', () => {
  it('prepends the comment header to the YAML output', async () => {
    const profile: ProjectProfile = {
      project: {
        type: 'single',
        tool: null,
        buildCommand: 'npm run build',
        testCommand: 'npm test',
      },
    }

    await writeProjectProfile('/project/.substrate/project-profile.yaml', profile)

    expect(mockWriteFile).toHaveBeenCalledOnce()
    const [, content] = mockWriteFile.mock.calls[0]
    const contentStr = String(content)

    expect(contentStr).toContain('# Substrate Project Profile')
    expect(contentStr).toContain('# Generated by `substrate init`')
    expect(contentStr).toContain('# Edit to override auto-detected settings.')
  })

  it('places the header before the YAML content', async () => {
    const profile: ProjectProfile = {
      project: {
        type: 'single',
        tool: null,
        buildCommand: 'go build ./...',
        testCommand: 'go test ./...',
      },
    }

    await writeProjectProfile('/project/.substrate/project-profile.yaml', profile)

    const [, content] = mockWriteFile.mock.calls[0]
    const contentStr = String(content)
    const headerEnd = contentStr.indexOf('# Edit to override auto-detected settings.')
    const yamlStart = contentStr.indexOf('project:')

    expect(headerEnd).toBeGreaterThan(-1)
    expect(yamlStart).toBeGreaterThan(headerEnd)
  })
})

// ---------------------------------------------------------------------------
// YAML serialization
// ---------------------------------------------------------------------------

describe('writeProjectProfile — YAML content', () => {
  it('serializes single project profile fields correctly', async () => {
    const profile: ProjectProfile = {
      project: {
        type: 'single',
        tool: null,
        language: 'go',
        buildTool: 'go',
        buildCommand: 'go build ./...',
        testCommand: 'go test ./...',
      },
    }

    await writeProjectProfile('/out/profile.yaml', profile)

    const [, content] = mockWriteFile.mock.calls[0]
    const contentStr = String(content)

    expect(contentStr).toContain('type: single')
    expect(contentStr).toContain('language: go')
    expect(contentStr).toContain('buildCommand: go build ./...')
    expect(contentStr).toContain('testCommand: go test ./...')
  })

  it('serializes monorepo profile with packages array', async () => {
    const profile: ProjectProfile = {
      project: {
        type: 'monorepo',
        tool: 'turborepo',
        buildCommand: 'turbo build',
        testCommand: 'turbo test',
        packages: [
          { path: 'apps/web', language: 'typescript', buildTool: 'pnpm' },
          { path: 'apps/lock-service', language: 'go', buildTool: 'go' },
        ],
      },
    }

    await writeProjectProfile('/out/profile.yaml', profile)

    const [, content] = mockWriteFile.mock.calls[0]
    const contentStr = String(content)

    expect(contentStr).toContain('type: monorepo')
    expect(contentStr).toContain('tool: turborepo')
    expect(contentStr).toContain('turbo build')
    expect(contentStr).toContain('apps/web')
    expect(contentStr).toContain('apps/lock-service')
    expect(contentStr).toContain('language: typescript')
    expect(contentStr).toContain('language: go')
  })

  it('writes to the specified profile path', async () => {
    const profile: ProjectProfile = {
      project: {
        type: 'single',
        buildCommand: 'cargo build',
        testCommand: 'cargo test',
      },
    }

    const targetPath = '/my-project/.substrate/project-profile.yaml'
    await writeProjectProfile(targetPath, profile)

    expect(mockWriteFile).toHaveBeenCalledWith(targetPath, expect.any(String), 'utf-8')
  })

  it('uses utf-8 encoding', async () => {
    const profile: ProjectProfile = {
      project: {
        type: 'single',
        buildCommand: 'npm run build',
        testCommand: 'npm test',
      },
    }

    await writeProjectProfile('/path/profile.yaml', profile)

    const [, , encoding] = mockWriteFile.mock.calls[0]
    expect(encoding).toBe('utf-8')
  })
})

// ---------------------------------------------------------------------------
// Round-trip correctness
// ---------------------------------------------------------------------------

describe('writeProjectProfile — round-trip', () => {
  it('YAML output can be parsed back to equivalent profile structure', async () => {
    const profile: ProjectProfile = {
      project: {
        type: 'monorepo',
        tool: 'turborepo',
        buildCommand: 'turbo build',
        testCommand: 'turbo test',
        packages: [
          { path: 'apps/api', language: 'typescript', buildTool: 'npm' },
        ],
      },
    }

    await writeProjectProfile('/path/profile.yaml', profile)

    const [, content] = mockWriteFile.mock.calls[0]
    const contentStr = String(content)

    // Strip header lines and parse the remainder
    const yamlLines = contentStr.split('\n').filter((l) => !l.startsWith('#'))
    const yaml = await import('js-yaml')
    const parsed = yaml.default.load(yamlLines.join('\n')) as ProjectProfile

    expect(parsed.project.type).toBe('monorepo')
    expect(parsed.project.tool).toBe('turborepo')
    expect(parsed.project.packages).toHaveLength(1)
    expect(parsed.project.packages?.[0].path).toBe('apps/api')
  })
})
