/**
 * Routing module — shared types for phase-level token tracking.
 *
 * References:
 *  - Epic 28, Story 28-6: Routing Telemetry — Per-Phase Token Tracking and OTEL Spans
 */

// ---------------------------------------------------------------------------
// PhaseTokenEntry
// ---------------------------------------------------------------------------

/**
 * Token usage attributed to a single (phase, model) combination during a pipeline run.
 */
export interface PhaseTokenEntry {
  /** Pipeline phase that consumed the tokens */
  phase: 'explore' | 'generate' | 'review' | 'default'
  /** Model identifier that handled the dispatches */
  model: string
  /** Cumulative input tokens across all dispatches in this bucket */
  inputTokens: number
  /** Cumulative output tokens across all dispatches in this bucket */
  outputTokens: number
  /** Number of agent dispatches attributed to this bucket */
  dispatchCount: number
}

// ---------------------------------------------------------------------------
// PhaseTokenBreakdown
// ---------------------------------------------------------------------------

/**
 * Aggregate phase-level token breakdown for a completed pipeline run.
 * Stored via StateStore at run completion and exposed in `substrate metrics`.
 */
export interface PhaseTokenBreakdown {
  /** One entry per distinct (phase, model) combination observed during the run */
  entries: PhaseTokenEntry[]
  /** Baseline model from the routing config (used for savings comparison in story 28-8) */
  baselineModel: string
  /** Pipeline run ID this breakdown belongs to */
  runId: string
}

// ---------------------------------------------------------------------------
// RoutingRecommendation
// ---------------------------------------------------------------------------

/**
 * A single routing recommendation suggesting a model change for a pipeline phase.
 * Generated by RoutingRecommender based on phase token breakdown history.
 */
export interface RoutingRecommendation {
  /** Pipeline phase this recommendation applies to (e.g. 'explore', 'generate', 'review') */
  phase: string
  /** Currently configured model for this phase */
  currentModel: string
  /** Suggested replacement model */
  suggestedModel: string
  /** Estimated percentage token cost savings (positive = cheaper) */
  estimatedSavingsPct: number
  /** Confidence level [0, 1] based on number of historical data points */
  confidence: number
  /** Number of pipeline runs used to compute this recommendation */
  dataPoints: number
  /** Direction of the suggested change */
  direction: 'upgrade' | 'downgrade'
}

// ---------------------------------------------------------------------------
// RoutingAnalysis
// ---------------------------------------------------------------------------

/**
 * Output of RoutingRecommender.analyze() — aggregate analysis of phase token
 * data across multiple pipeline runs.
 */
export interface RoutingAnalysis {
  /** All generated recommendations (may be empty if data is insufficient or ratios are neutral) */
  recommendations: RoutingRecommendation[]
  /** Number of pipeline runs analyzed */
  analysisRuns: number
  /** True when fewer than 3 historical breakdowns are available */
  insufficientData: boolean
  /** Per-phase output ratio (output / (input + output)) */
  phaseOutputRatios: Record<string, number>
}

// ---------------------------------------------------------------------------
// TuneLogEntry
// ---------------------------------------------------------------------------

/**
 * Audit log entry written by RoutingTuner when it auto-applies a model downgrade.
 */
export interface TuneLogEntry {
  /** Unique identifier for this log entry */
  id: string
  /** Pipeline run ID that triggered the auto-tune */
  runId: string
  /** Phase whose model was changed */
  phase: string
  /** Model that was in use before the change */
  oldModel: string
  /** Model that replaced it */
  newModel: string
  /** Estimated percentage savings from the change */
  estimatedSavingsPct: number
  /** ISO 8601 timestamp when the change was applied */
  appliedAt: string
}
