/**
 * Recommendation Types — data structures for the routing recommendations engine.
 *
 * These types represent the output of the RecommendationEngine:
 * - Recommendation: A single routing recommendation comparing two agents
 * - RecommendationFilters: Configuration for filtering recommendations
 * - ConfidenceLevel: Confidence tier based on sample size
 *
 * Architecture: Advisory-only recommendations; never override explicit policy (FR68).
 * Zero LLM calls — all computation is pure statistical processing.
 */

// ---------------------------------------------------------------------------
// ConfidenceLevel
// ---------------------------------------------------------------------------

/**
 * Confidence tier for a routing recommendation, based on sample size:
 *  - "high": both agents have >= 50 tasks
 *  - "medium": both agents have >= 20 but < 50 tasks
 *  - "low": both agents have >= min_sample_size but < 20 tasks (for either agent)
 */
export type ConfidenceLevel = 'low' | 'medium' | 'high'

// ---------------------------------------------------------------------------
// Recommendation interface
// ---------------------------------------------------------------------------

/**
 * A single routing recommendation generated by the RecommendationEngine.
 * Produced when one agent shows a statistically meaningful advantage over
 * another for a given task type (FR68).
 */
export interface Recommendation {
  /** The category of work this recommendation applies to (e.g., "coding", "testing") */
  task_type: string

  /** The agent currently being used for this task type */
  current_agent: string

  /** The agent showing better performance for this task type */
  recommended_agent: string

  /**
   * Human-readable explanation of the recommendation.
   * Example: "claude-opus-4-6 shows 15% higher success rate for coding tasks (82% vs 67%, based on 52 tasks)"
   */
  reason: string

  /** Confidence tier based on sample size */
  confidence: ConfidenceLevel

  /** Success rate of the current agent (0–100%) */
  current_success_rate: number

  /** Success rate of the recommended agent (0–100%) */
  recommended_success_rate: number

  /** Average tokens per task for the current agent */
  current_avg_tokens: number

  /** Average tokens per task for the recommended agent */
  recommended_avg_tokens: number

  /**
   * Percentage point improvement: recommended_success_rate - current_success_rate.
   * Always >= threshold (default 5.0) for a recommendation to be generated.
   */
  improvement_percentage: number

  /** Number of tasks used to compute current agent's success rate */
  sample_size_current: number

  /** Number of tasks used to compute recommended agent's success rate */
  sample_size_recommended: number
}

// ---------------------------------------------------------------------------
// RecommendationFilters
// ---------------------------------------------------------------------------

/**
 * Configuration filters that control which recommendations are generated.
 * Sourced from OrchestratorConfig.monitor settings (AC6).
 */
export interface RecommendationFilters {
  /**
   * Minimum success rate improvement (percentage points) required to generate
   * a recommendation. Default: 5.0 (i.e., >= 5% improvement).
   */
  threshold_percentage: number

  /**
   * Minimum number of tasks required per (agent, task_type) pair before a
   * recommendation will be generated. Default: 10.
   */
  min_sample_size: number
}

// ---------------------------------------------------------------------------
// RecommendationExport (Task 7 — for CLI output in Story 8.7)
// ---------------------------------------------------------------------------

/**
 * JSON-serializable export structure for CLI and report output (Task 7).
 */
export interface RecommendationExport {
  generated_at: string
  count: number
  recommendations: Recommendation[]
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * Create and validate a Recommendation object from raw data.
 * Performs basic type coercion and field validation.
 *
 * Throws if required fields are missing or invalid.
 */
export function createRecommendation(data: unknown): Recommendation {
  if (data === null || typeof data !== 'object') {
    throw new Error('createRecommendation: data must be an object')
  }

  const d = data as Record<string, unknown>

  const requiredString = (field: string): string => {
    const val = d[field]
    if (typeof val !== 'string' || val.length === 0) {
      throw new Error(`createRecommendation: missing or invalid field "${field}"`)
    }
    return val
  }

  const requiredNumber = (field: string): number => {
    const val = d[field]
    if (typeof val !== 'number' || !isFinite(val)) {
      throw new Error(`createRecommendation: missing or invalid field "${field}"`)
    }
    return val
  }

  const confidence = d['confidence']
  if (confidence !== 'low' && confidence !== 'medium' && confidence !== 'high') {
    throw new Error(
      `createRecommendation: confidence must be "low", "medium", or "high", got "${String(confidence)}"`,
    )
  }

  return {
    task_type: requiredString('task_type'),
    current_agent: requiredString('current_agent'),
    recommended_agent: requiredString('recommended_agent'),
    reason: requiredString('reason'),
    confidence: confidence as ConfidenceLevel,
    current_success_rate: requiredNumber('current_success_rate'),
    recommended_success_rate: requiredNumber('recommended_success_rate'),
    current_avg_tokens: requiredNumber('current_avg_tokens'),
    recommended_avg_tokens: requiredNumber('recommended_avg_tokens'),
    improvement_percentage: requiredNumber('improvement_percentage'),
    sample_size_current: requiredNumber('sample_size_current'),
    sample_size_recommended: requiredNumber('sample_size_recommended'),
  }
}
