/**
 * Shared types for the Debate Panel module.
 */

// ---------------------------------------------------------------------------
// Decision tier
// ---------------------------------------------------------------------------

/**
 * Classification for how significant a decision is.
 * Determines the number of perspectives and voting rules.
 */
export type DecisionTier = 'routine' | 'significant' | 'architectural'

// ---------------------------------------------------------------------------
// Decision request
// ---------------------------------------------------------------------------

/**
 * Input to `debatePanel.decide()`.
 */
export interface DecisionRequest {
  /** How significant this decision is */
  tier: DecisionTier
  /** The question or decision to be made */
  question: string
  /** Supporting context for the decision */
  context: string
  /** Number of perspectives to solicit (significant tier; defaults to 3) */
  perspectives?: number
  /**
   * Optional pipeline run ID for decision persistence.
   * Used when persisting to the decision store via `createDecision`.
   */
  pipelineRunId?: string
  /**
   * Optional key for the decision record.
   * Defaults to a sanitized version of the question.
   */
  key?: string
  /**
   * Optional phase for the decision record.
   * Defaults to the decision tier.
   */
  phase?: string
}

// ---------------------------------------------------------------------------
// Perspective
// ---------------------------------------------------------------------------

/**
 * A single perspective on a decision, generated by a sub-agent.
 */
export interface Perspective {
  /** The viewpoint label (e.g., 'simplicity', 'performance', 'security') */
  viewpoint: string
  /** The perspective's recommended course of action */
  recommendation: string
  /** Confidence in this recommendation (0.0–1.0) */
  confidence: number
  /** Identified risks associated with this recommendation */
  risks: string[]
}

// ---------------------------------------------------------------------------
// Voting record
// ---------------------------------------------------------------------------

/**
 * Record of the weighted voting process for significant/architectural decisions.
 */
export interface VotingRecord {
  /** Individual vote weights per viewpoint */
  votes: { viewpoint: string; weight: number }[]
  /** The winning recommendation */
  winner: string
  /** Margin of victory (0.0–1.0) */
  margin: number
  /** Whether a tie-break perspective was solicited */
  tieBreak: boolean
}

// ---------------------------------------------------------------------------
// Debate result
// ---------------------------------------------------------------------------

/**
 * Final result of a `debatePanel.decide()` call.
 */
export interface DebateResult {
  /** The final decision recommendation */
  decision: string
  /** Rationale for the decision */
  rationale: string
  /** The decision tier that was used */
  tier: DecisionTier
  /** All perspectives collected */
  perspectives: Perspective[]
  /** Voting record (only present for significant/architectural tiers) */
  votingRecord?: VotingRecord
  /**
   * Whether the decision was escalated to the user.
   * Only true for architectural decisions that did not achieve supermajority.
   */
  escalated?: boolean
}
