// src/persistence/queries/decisions.ts — re-export shim (migrated to packages/core in story 41-3)
export {
  createDecision,
  upsertDecision,
  getDecisionsByPhase,
  getDecisionsByPhaseForRun,
  getDecisionsByCategory,
  getDecisionByKey,
  updateDecision,
  createRequirement,
  listRequirements,
  updateRequirementStatus,
  createConstraint,
  listConstraints,
  registerArtifact,
  getArtifactsByPhase,
  getArtifactByType,
  getArtifactByTypeForRun,
  getArtifactsByRun,
  getPipelineRunById,
  updatePipelineRunConfig,
  createPipelineRun,
  updatePipelineRun,
  getRunningPipelineRuns,
  getLatestRun,
  addTokenUsage,
  getTokenUsageSummary,
} from '@substrate-ai/core'
export type {
  Decision,
  Requirement,
  Constraint,
  Artifact,
  PipelineRun,
  TokenUsage,
  CreateDecisionInput,
  CreateRequirementInput,
  CreateConstraintInput,
  RegisterArtifactInput,
  CreatePipelineRunInput,
  AddTokenUsageInput,
  TokenUsageSummary,
} from '@substrate-ai/core'
