/**
 * Type definitions for the WorkerAdapter subsystem
 * All adapter types are defined here for consistency and reuse
 */

import type { AgentId, BillingMode, TaskId } from '../types.js'

/**
 * A spawn command descriptor that the orchestrator uses to invoke a CLI agent.
 * Contains all information needed to execute an agent process.
 */
export interface SpawnCommand {
  /** The binary to execute (e.g., "claude", "codex", "gemini") */
  binary: string
  /** Arguments to pass to the binary */
  args: string[]
  /** Optional environment variable overrides */
  env?: Record<string, string>
  /** Optional list of environment variable keys to unset in the child process */
  unsetEnvKeys?: string[]
  /** Working directory for the process */
  cwd: string
  /** Optional data to pipe to stdin */
  stdin?: string
  /** Optional timeout in milliseconds */
  timeoutMs?: number
}

/**
 * Options passed to adapter methods for each invocation.
 * Controls execution context for a specific task run.
 */
export interface AdapterOptions {
  /** Path to the git worktree for this task */
  worktreePath: string
  /** Billing mode to use for this execution */
  billingMode: BillingMode
  /** Optional model identifier override */
  model?: string
  /** Optional additional CLI flags to append */
  additionalFlags?: string[]
  /** Optional API key override (used when billingMode is 'api') */
  apiKey?: string
  /** Optional maximum agentic turns (passed as --max-turns to Claude CLI) */
  maxTurns?: number
  /**
   * Optional OTLP endpoint URL for telemetry export (Story 27-9).
   * When set, injects OTLP env vars into the spawned process so that
   * Claude Code exports telemetry to the local IngestionServer.
   * Example: "http://localhost:4318"
   */
  otlpEndpoint?: string
  /**
   * Optional story key for OTEL resource attribute tagging.
   * Injected as `substrate.story_key` via OTEL_RESOURCE_ATTRIBUTES
   * so the telemetry pipeline can group spans/events per story.
   */
  storyKey?: string
  /**
   * Optional maximum context tokens (passed as --max-context-tokens to Claude CLI).
   * When set, constrains the context window to prevent runaway token usage.
   * Used by efficiency-gated retry logic (Story 30-8) to cap context for stories
   * that previously exhibited context spike patterns.
   */
  maxContextTokens?: number
  /**
   * Optional optimization directives derived from prior stories' telemetry (Story 30-6).
   * When set, appended to the system prompt to guide the sub-agent toward efficient patterns.
   * Generated by TelemetryAdvisor.formatOptimizationDirectives().
   */
  optimizationDirectives?: string
  /** Dispatch context: task type (create-story, dev-story, code-review, etc.) for OTLP attribution */
  taskType?: string
  /** Dispatch context: unique dispatch ID for per-dispatch telemetry correlation */
  dispatchId?: string
}

/**
 * Capabilities reported by an adapter for this CLI agent.
 * Used for routing and planning decisions.
 */
export interface AdapterCapabilities {
  /** Whether the agent outputs structured JSON */
  supportsJsonOutput: boolean
  /** Whether the agent supports streaming output */
  supportsStreaming: boolean
  /** Whether the agent supports subscription-based billing */
  supportsSubscriptionBilling: boolean
  /** Whether the agent supports API-key-based billing */
  supportsApiBilling: boolean
  /** Whether the agent can generate task planning graphs */
  supportsPlanGeneration: boolean
  /** Maximum context tokens the agent supports */
  maxContextTokens: number
  /** Task types this agent can handle */
  supportedTaskTypes: string[]
  /** Programming languages the agent supports */
  supportedLanguages: string[]
  /**
   * Timeout multiplier relative to default dispatch timeouts.
   * Agents that are slower (e.g., Codex) declare a multiplier > 1.0
   * so the dispatcher scales timeouts automatically.
   * Default: 1.0 (no scaling).
   */
  timeoutMultiplier?: number
  /**
   * Whether the agent supports a --system-prompt flag.
   * Claude Code: true. Codex/Gemini: false.
   * When false, system-level instructions must be embedded in the prompt itself.
   */
  supportsSystemPrompt?: boolean
  /**
   * Whether the agent exports OTLP telemetry (spans, metrics, logs).
   * Claude Code: true. Codex/Gemini: false.
   * When false, telemetry is heuristic-only (character-based token estimates).
   */
  supportsOtlpExport?: boolean
  /**
   * Whether the dispatcher should append a YAML output format reminder to prompts.
   * Claude Code: false (follows methodology pack format instructions reliably).
   * Codex/Gemini: true (need explicit final nudge to emit fenced YAML blocks).
   */
  requiresYamlSuffix?: boolean
  /**
   * Default maximum review cycles for this agent backend.
   * Claude Code: 2 (converges quickly). Codex: 3 (needs more iterations).
   * Overridden by explicit --max-review-cycles CLI flag.
   */
  defaultMaxReviewCycles?: number
}

/**
 * Result returned from an adapter health check.
 * Indicates whether the CLI binary is present and functional.
 */
export interface AdapterHealthResult {
  /** Whether the adapter is considered healthy and usable */
  healthy: boolean
  /** Detected version string of the CLI binary */
  version?: string
  /** Full path to the CLI binary, if resolved */
  cliPath?: string
  /** Error message when healthy is false */
  error?: string
  /** Detected billing mode(s) available for this adapter */
  detectedBillingModes?: BillingMode[]
  /** Whether the CLI supports headless/non-interactive mode */
  supportsHeadless: boolean
}

/**
 * Parsed result from a task execution.
 * Normalized representation from CLI agent JSON output.
 */
export interface TaskResult {
  /** Task identifier this result belongs to */
  taskId?: TaskId
  /** Whether the task completed successfully */
  success: boolean
  /** Primary output content from the agent */
  output: string
  /** Error message if the task failed */
  error?: string
  /** Raw exit code from the CLI process */
  exitCode: number
  /** Execution metadata */
  metadata?: {
    executionTime?: number
    tokensUsed?: TokenEstimate
  }
  /**
   * True when the dispatcher's AdapterOutputNormalizer exhausted all
   * normalization strategies without extracting parseable YAML.
   * Authoritative signal for the 'adapter-format' root cause category (story 53-10).
   * Optional — existing callers without the field continue to compile unchanged.
   */
  adapterError?: boolean
}

/**
 * Token usage estimate for budget tracking.
 */
export interface TokenEstimate {
  /** Estimated input tokens */
  input: number
  /** Estimated output tokens */
  output: number
  /** Total token estimate */
  total: number
}

/**
 * Request input for plan generation.
 */
export interface PlanRequest {
  /** High-level goal or description of work to plan */
  goal: string
  /** Additional context for the planning agent */
  context?: string
  /** Maximum number of tasks to generate */
  maxTasks?: number
}

/**
 * Parsed result from a plan generation invocation.
 */
export interface PlanParseResult {
  /** Whether plan generation succeeded */
  success: boolean
  /** Parsed list of planned task descriptions */
  tasks: PlannedTask[]
  /** Error message if plan generation failed */
  error?: string
  /** Raw output for debugging */
  rawOutput?: string
}

/**
 * A single task entry in a generated plan.
 */
export interface PlannedTask {
  /** Task title */
  title: string
  /** Detailed description */
  description: string
  /** Estimated complexity (1-10) */
  complexity?: number
  /** Other task titles this task depends on */
  dependencies?: string[]
}

/**
 * Result from a single adapter discovery attempt.
 */
export interface AdapterDiscoveryResult {
  /** Adapter id that was tried */
  adapterId: AgentId
  /** Display name of the adapter */
  displayName: string
  /** Health check result */
  healthResult: AdapterHealthResult
  /** Whether the adapter was registered (healthy) */
  registered: boolean
}

/**
 * Summary result from discoverAndRegister().
 */
export interface DiscoveryReport {
  /** Number of adapters successfully registered */
  registeredCount: number
  /** Number of adapters that failed health checks */
  failedCount: number
  /** Per-adapter detail results */
  results: AdapterDiscoveryResult[]
}

